name: 🧪 Backend CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  backend-ci:
    name: Build, Lint & Test (Backend)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js with cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm" # Automatically caches node_modules via package-lock.json

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run ESLint
      - name: Lint code
        run: npx eslint .

      #  Run tests with Jest and generate coverage
      - name: Run Jest tests with coverage
        run: npm test -- --passWithNoTests --coverage

      #  Upload Jest coverage report (optional)
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: server/coverage
